org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-17
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=false
android.nonFinalResIds=false
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
